export enum Forbidden {
    DEFAULT = "You do not have permission to perform this action.",
    DEFAULT_NOT_ENOUGH_TOKENS = "You do not have enough tokens to perform this action.",
    DEFAULT_NOT_ENOUGH_DIAMONDS = "You do not have enough diamonds to perform this action.",
    AUTH_BANNED = "You are currently banned for %s. Your ban will expire %s. If you believe this is a mistake, please contact a staff member.",
    SETTINGS_REVOKED_CHANGE_USERNAME = "Your permission to change your username has been revoked by an administrator.",
    REPORTS_REVOKED_CREATE_REPORT = "Your permission to create reports has been revoked by an administrator.",
    PACKS_NOT_ENOUGH_TOKENS = "You do not have enough tokens to purchase this pack.",
    BLOOKS_NOT_ENOUGH_BLOOKS = "You do not have enough blooks to perform this action.",
    ITEMS_NOT_ENOUGH_ITEMS = "You do not have enough items to perform this action.",
    AUCTIONS_BUY_IT_NOW_NOT_ENOUGH_DIAMONDS = "You do not have enough diamonds to purchase this listing.",
    AUCTIONS_BUY_IT_NOW_OWN_AUCTION = "You cannot purchase your own listing.",
    AUCTIONS_BID_NOT_ENOUGH_DIAMONDS = "You do not have enough diamonds to place this bid.",
    AUCTIONS_BID_OWN_AUCTION = "You cannot bid on your own listing.",
    AUCTIONS_BID_TOO_LOW = "Your bid is too low. The minimum bid is %s.",
    AUCTIONS_BID_OWN_BID = "You are already the highest bidder.",
    AUCTIONS_REMOVE_HAS_BIDS = "You cannot remove a listing with bids.",
    CHAT_ROOM_NO_PERMISSION = "You do not have permission to access this chat room.",
    CHAT_MESSAGE_NO_PERMISSION = "You do not have permission to perform actions on this message.",
    CHAT_MUTED = "You are currently muted for %s. Your mute will expire %s. If you believe this is a mistake, please contact a staff member.",
    QUESTS_DAILY_ALREADY_CLAIMED = "You have already claimed your daily tokens.",
    AUCTIONS_TAX_NOT_ENOUGH_DIAMONDS = "You do not have enough diamonds to create an auction.",
    COSMETICS_TITLES_NOT_OWNED = "You do not own this title.",
    COSMETICS_FONTS_NOT_OWNED = "You do not own this font."
};
